redisson:
  address: redis://${spring.redis.host}:${spring.redis.port}        # redis地址
  timeout: 3000                                                     # 超时时间
  connectionPoolSize: 64                                            # 连接池大小 默认64
  connectionMinimumIdleSize: 32